var_categ_good = ['FLAG_EMP_PHONE', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'REGION_RATING_CLIENT'
                  'REGION_RATING_CLIENT_W_CITY']

var_categ_tri = ["FLAG_WORK_PHONE", "FLAG_PHONE", "LIVE_CITY_NOT_WORK_CITY"]

var_categ_bad = [ "FLAG_MOBIL", "FLAG_CONT_MOBILE", "FLAG_EMAIL"
                  'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION',
                  'LIVE_REGION_NOT_WORK_REGION', 'FLAG_WORK_PHONE', "AMT_REG_CREDIT_BUREAU_QRT",
                  "AMT_REG_CREDIT_BUREAU_WEEK", "AMT_REG_CREDIT_BUREAU_DAY", "AMT_REG_CREDIT_BUREAU_HOUR"]

var_categ_regroup = ["CNT_CHILDREN", "CNT_FAM_MEMBERS", "DEF_30_CNT_SOCIAL_CIRCLE", "DEF_60_CNT_SOCIAL_CIRCLE"]